/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>

#include "rand.h"

void *
initialize_random_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

double *
get_next_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static double  result;

	result += 0.31;
	if(result >= 1.0)
		result = (double) rand()/RAND_MAX*100 + 1.0;


	return &result;
}
