#include <iostream>
#include <string>

#include "Instructor.h"

using namespace std;

Instructor::Instructor(): Person(), salary(0)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:0000000000000888 begin
{
}
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:0000000000000888 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Instructor::Instructor(string n, string d, string g, int s): Person(n,d,g), salary(s)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:000000000000088A begin
{
}
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:000000000000088A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Instructor::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:0000000000000898 begin
{
	if(gender == "M")
		cout << "Mr. ";
	else
		cout << "Ms. ";
	Person::print();
	cout << "	Instructor, Salary: " << salary << endl;
}
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:0000000000000898 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
