#include <iostream>
#include <string>

#include "Person.h"

using namespace std;

Person::Person(): name(""), dob(""), gender("")
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:000000000000086D begin
{
}
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:000000000000086D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Person::Person(string n, string d, string g): name(n), dob(d), gender(g)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:0000000000000883 begin
{
}
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:0000000000000883 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Person::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:0000000000000896 begin
{
	cout << name << " " << dob << endl;
}
// section -117--74--108--126-4571c031:1547e2e8c07:-8000:0000000000000896 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
